package com.ssu.ChernousovaYA.snake.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.ssu.ChernousovaYA.snake.model.Parametrs;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Juli on 23.02.2017.
 */
public class FormSetting extends JFrame {

    private static int n;
    private static int m;
    private static int len;
    private static int intCountFrogs;
    private static int speed;
    public GUI parrent;
    private JTextField textField1;
    private JTextField textField2;
    private JPanel panel1;
    private JButton backButton;
    private JTextField length;
    private JTextField speedText;
    private JLabel labelSpeed;

    public void setParrent(GUI parrent) {
        this.parrent = parrent;
    }

    public FormSetting get() {
        return this;
    }

    public FormSetting(Parametrs param) {
        n = param.getN();
        m = param.getM();
        len = param.getLength();

        intCountFrogs = param.getCount();
        speed = param.getSpeed();

        $$$setupUI$$$();
        setContentPane(panel1);
        this.setBounds(400, 400, 400, 300);
        textField1.setText(Integer.toString(n));
        textField2.setText(Integer.toString(m));
        length.setText(Integer.toString(len));
        speedText.setText(Integer.toString(speed));


        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        backButton.addActionListener(
                e -> {
                    setVisible(false);
                    parrent.dispose();
                    param.setN(Integer.valueOf(textField1.getText()));
                    param.setM(Integer.valueOf(textField2.getText()));
                    param.setLength(Integer.valueOf(length.getText()));
                    // param.setCount(Integer.valueOf(count.getText()));
                    param.setSpeed(Integer.valueOf(speedText.getText()));
                    parrent = new GUI(param);
                    parrent.setChild(get());
                });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-16777216));
        panel2.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-13575640));
        label1.setText("Width:");
        panel1.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-13575640));
        label2.setText("Heidth:");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-13575640));
        label3.setText("Setting");
        panel1.add(label3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField2 = new JTextField();
        textField2.setBackground(new Color(-2695207));
        textField2.setText("");
        panel1.add(textField2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        backButton = new JButton();
        backButton.setBackground(new Color(-16777216));
        backButton.setForeground(new Color(-13575640));
        backButton.setText("Back");
        panel1.add(backButton, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setForeground(new Color(-13575640));
        label4.setText("Length snake:");
        panel1.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        textField1.setBackground(new Color(-2695207));
        panel1.add(textField1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        length = new JTextField();
        length.setBackground(new Color(-2695207));
        panel1.add(length, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        speedText = new JTextField();
        speedText.setBackground(new Color(-2695207));
        panel1.add(speedText, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelSpeed = new JLabel();
        labelSpeed.setForeground(new Color(-13575640));
        labelSpeed.setText("Speed snake:");
        panel1.add(labelSpeed, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }
}
